import PupilProfileReport from "../reports/education/report001";
import ToolkitExample from "../reports/education/report002";
import ToolkitReportCard from "../components/ToolkitReportCard";

// Simple placeholder for Toolkit school cards
const ToolkitPlaceholder = ({ name }) => (
  <div style={{
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    fontWeight: "bold",
    fontSize: 20,
    textAlign: "center",
    padding: 8,
  }}>
    {name}
  </div>
);

export const reportConfig = [
  // Example education report
  {
    id: "pupil-profile",
    name: "Pupil Profile",
    description: "Indepth Pupil Profile.",
    category: "Education",
    tag: "New",
    href: "/analytics/report/pupil-profile",
    component: PupilProfileReport,
    comingSoon: false,
  },
  // Example toolkit page/report
  {
    id: "toolkit-example",
    name: "Toolkit",
    description: "Toolkit Example.",
    category: "Toolkit",
    tag: "New",
    href: "/analytics/report/toolkit-example",
    component: ToolkitExample,
    comingSoon: false,
  },
  // Example coming soon card
  { id: "003", comingSoon: true },

  // --- 34 Toolkit School Cards (all plain objects, copy-paste ready) ---
  {
    id: "toolkit-1",
    name: "Abbey CE Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/abbey-ce-academy",
    component: () => <ToolkitPlaceholder name="Abbey CE Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-2",
    name: "Ainthorpe Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/ainthorpe-primary-school",
    component: () => <ToolkitPlaceholder name="Ainthorpe Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-3",
    name: "Booth Wood Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/booth-wood-academy",
    component: () => <ToolkitPlaceholder name="Booth Wood Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-4",
    name: "Briar Hill Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/briar-hill-primary-school",
    component: () => <ToolkitPlaceholder name="Briar Hill Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-5",
    name: "Bringhurst Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/bringhurst-primary-school",
    component: () => <ToolkitPlaceholder name="Bringhurst Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-6",
    name: "Cedar Road Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/cedar-road-primary-school",
    component: () => <ToolkitPlaceholder name="Cedar Road Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-7",
    name: "Eastfield Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/eastfield-academy",
    component: () => <ToolkitPlaceholder name="Eastfield Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-8",
    name: "Edward Heneage Primary Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/edward-heneage-primary-academy",
    component: () => <ToolkitPlaceholder name="Edward Heneage Primary Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-9",
    name: "Endike Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/endike-academy",
    component: () => <ToolkitPlaceholder name="Endike Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-10",
    name: "Fairfield Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/fairfield-academy",
    component: () => <ToolkitPlaceholder name="Fairfield Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-11",
    name: "Falconer's Hill Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/falconers-hill-academy",
    component: () => <ToolkitPlaceholder name="Falconer's Hill Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-12",
    name: "Greenfields Primary School and Nursery",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/greenfields-primary-school-and-nursery",
    component: () => <ToolkitPlaceholder name="Greenfields Primary School and Nursery" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-13",
    name: "Hogsthorpe Primary Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/hogsthorpe-primary-academy",
    component: () => <ToolkitPlaceholder name="Hogsthorpe Primary Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-14",
    name: "Ingoldsby Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/ingoldsby-academy",
    component: () => <ToolkitPlaceholder name="Ingoldsby Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-15",
    name: "Kings Heath Primary Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/kings-heath-primary-academy",
    component: () => <ToolkitPlaceholder name="Kings Heath Primary Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-16",
    name: "Malcolm Arnold Preparatory School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/malcolm-arnold-preparatory-school",
    component: () => <ToolkitPlaceholder name="Malcolm Arnold Preparatory School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-17",
    name: "Newnham Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/newnham-primary-school",
    component: () => <ToolkitPlaceholder name="Newnham Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-18",
    name: "Quay Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/quay-academy",
    component: () => <ToolkitPlaceholder name="Quay Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-19",
    name: "Rockingham Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/rockingham-primary-school",
    component: () => <ToolkitPlaceholder name="Rockingham Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-20",
    name: "The Arbours Primary School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/the-arbours-primary-school",
    component: () => <ToolkitPlaceholder name="The Arbours Primary School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-21",
    name: "The Richmond Primary Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/the-richmond-primary-academy",
    component: () => <ToolkitPlaceholder name="The Richmond Primary Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-22",
    name: "Thomas Hinderwell Primary Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/thomas-hinderwell-primary-academy",
    component: () => <ToolkitPlaceholder name="Thomas Hinderwell Primary Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-23",
    name: "Wold Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/wold-academy",
    component: () => <ToolkitPlaceholder name="Wold Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-24",
    name: "Welton CE Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/welton-ce-academy",
    component: () => <ToolkitPlaceholder name="Welton CE Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-25",
    name: "Barnes Wallis Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/barnes-wallis-academy",
    component: () => <ToolkitPlaceholder name="Barnes Wallis Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-26",
    name: "Charles Read Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/charles-read-academy",
    component: () => <ToolkitPlaceholder name="Charles Read Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-27",
    name: "Charnwood College",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/charnwood-college",
    component: () => <ToolkitPlaceholder name="Charnwood College" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-28",
    name: "Havelock Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/havelock-academy",
    component: () => <ToolkitPlaceholder name="Havelock Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-29",
    name: "Humberston Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/humberston-academy",
    component: () => <ToolkitPlaceholder name="Humberston Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-30",
    name: "King Edward VI Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/king-edward-vi-academy",
    component: () => <ToolkitPlaceholder name="King Edward VI Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-31",
    name: "Lodge Park Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/lodge-park-academy",
    component: () => <ToolkitPlaceholder name="Lodge Park Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-32",
    name: "Malcolm Arnold Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/malcolm-arnold-academy",
    component: () => <ToolkitPlaceholder name="Malcolm Arnold Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-33",
    name: "Skegness Grammar School",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/skegness-grammar-school",
    component: () => <ToolkitPlaceholder name="Skegness Grammar School" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  },
  {
    id: "toolkit-34",
    name: "Thomas Middlecott Academy",
    description: "",
    category: "Toolkit",
    tag: "",
    href: "/analytics/toolkit/thomas-middlecott-academy",
    component: () => <ToolkitPlaceholder name="Thomas Middlecott Academy" />,
    cardComponent: ToolkitReportCard,
    comingSoon: false,
  }
];