import EducationReports from "../reports/education/report001";
import AttendanceOverviewReport from "../reports/education/report002";

export const reportConfig = [
  {
    id: "education-analytics",
    name: "Education Analytics",
    description: "All education-related analytics and reports.",
    category: "Education",
    tag: "",
    href: "/analytics/education/education-analytics",
    component: EducationReports,
    comingSoon: false,
  },
  {
    id: "attendance-overview",
    name: "Attendance Overview",
    description: "Track attendance across the trust.",
    category: "Education",
    tag: "New",
    href: "/analytics/education/attendance-overview",
    component: AttendanceOverviewReport,
    comingSoon: false,
  },
  {
    id: "mock-001",
    name: "KS4 Performance",
    description: "Explore attainment trends at KS4.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-001",
    component: AttendanceOverviewReport,
    comingSoon: false,
  },
  {
    id: "mock-002",
    name: "KS2 SATs Summary",
    description: "View SATs outcomes and cohort comparison.",
    category: "Education",
    tag: "Hot",
    href: "/analytics/education/mock-002",
    comingSoon: false,
  },
  {
    id: "mock-003",
    name: "Reading Progress",
    description: "Monitor reading age and comprehension progress.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-003",
    comingSoon: false,
  },
  {
    id: "mock-004",
    name: "Behaviour Dashboard",
    description: "Review behaviour points and exclusions.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-004",
    comingSoon: false,
  },
  {
    id: "mock-005",
    name: "SEN Provision Map",
    description: "Visualise SEND support by pupil and need.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-005",
    comingSoon: false,
  },
  {
    id: "mock-006",
    name: "Staff Absence Trends",
    description: "Analyse patterns in staff absence by academy.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-006",
    comingSoon: false,
  },
  {
    id: "mock-007",
    name: "Subject Progress Overview",
    description: "Compare progress across all core subjects.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-007",
    comingSoon: false,
  },
  {
    id: "mock-008",
    name: "Pupil Premium Impact",
    description: "Track outcomes for disadvantaged learners.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-008",
    comingSoon: false,
  },
  {
    id: "mock-009",
    name: "Phonics Tracker",
    description: "Monitor phonics scores and intervention progress.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-009",
    comingSoon: false,
  },
  {
    id: "mock-010",
    name: "Early Years Overview",
    description: "Snapshot of EYFS assessments and development.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-010",
    comingSoon: false,
  },
  {
    id: "mock-011",
    name: "Safeguarding Incidents",
    description: "View recorded concerns and outcomes over time.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-011",
    comingSoon: false,
  },
  {
    id: "mock-012",
    name: "Homework Engagement",
    description: "Track homework submissions and quality ratings.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-012",
    comingSoon: false,
  },
  {
    id: "mock-013",
    name: "Progress 8 Breakdown",
    description: "Detailed Progress 8 scores by subject and pupil group.",
    category: "Education",
    tag: "",
    href: "/analytics/education/mock-013",
    comingSoon: false,
  }
];
