import PowerBIReportPage from "../reports/education/report";

export const reportConfig = [
  {
    id: "dret-pupil-profile",
    name: "DRET Pupil Profile",
    description: "View detailed profile data for each pupil.",
    category: "DRET",
    tag: "",
    href: "/analytics/education/dret-pupil-profile",
    component: () => <PowerBIReportPage reportKey="dret-pupil-profile" title="DRET Pupil Profile" />,
    comingSoon: false,
  },
  {
    id: "dret-education-team-report",
    name: "Education Team Report",
    description: "Trust-level metrics used by the central team.",
    category: "DRET",
    tag: "",
    href: "/analytics/education/dret-education-team-report",
    component: () => <PowerBIReportPage reportKey="dret-education-team-report" title="Education Team Report" />,
    comingSoon: false,
  },
  {
    id: "bromcom-attendance",
    name: "Attendance Overview",
    description: "Track attendance across the trust.",
    category: "Bromcom",
    tag: "New",
    href: "/analytics/education/bromcom-attendance",
    component: () => <PowerBIReportPage reportKey="bromcom-attendance" title="Attendance Overview" />,
    comingSoon: false,
  },
  {
    id: "bromcom-eyf-stage-assessment",
    name: "EYF Stage Assessment",
    description: "EYFS stage-level outcomes and progress.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-eyf-stage-assessment",
    component: () => <PowerBIReportPage reportKey="bromcom-eyf-stage-assessment" title="EYF Stage Assessment" />,
    comingSoon: false,
  },
  {
    id: "bromcom-formative-assessment",
    name: "Formative Assessment",
    description: "Track formative progress over time.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-formative-assessment",
    component: () => <PowerBIReportPage reportKey="bromcom-formative-assessment" title="Formative Assessment" />,
    comingSoon: false,
  },
  {
    id: "bromcom-ks1-ks2-assessment",
    name: "KS1/KS2 Assessment",
    description: "View assessment performance at KS1 and KS2.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-ks1-ks2-assessment",
    component: () => <PowerBIReportPage reportKey="bromcom-ks1-ks2-assessment" title="KS1/KS2 Assessment" />,
    comingSoon: false,
  },
  {
    id: "bromcom-ks1-ks2-tracker",
    name: "KS1/KS2 Tracker",
    description: "Cohort-level tracking across subjects.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-ks1-ks2-tracker",
    component: () => <PowerBIReportPage reportKey="bromcom-ks1-ks2-tracker" title="KS1/KS2 Tracker" />,
    comingSoon: false,
  },
  {
    id: "bromcom-ks4-performance",
    name: "KS4 Performance",
    description: "GCSE and equivalent attainment data.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-ks4-performance",
    component: () => <PowerBIReportPage reportKey="bromcom-ks4-performance" title="KS4 Performance" />,
    comingSoon: false,
  },
  {
    id: "bromcom-mat-performance-overview",
    name: "MAT Performance Overview",
    description: "Trust-wide headline performance figures.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-mat-performance-overview",
    component: () => <PowerBIReportPage reportKey="bromcom-mat-performance-overview" title="MAT Performance Overview" />,
    comingSoon: false,
  },
  {
    id: "bromcom-suspensions-exclusions",
    name: "Suspensions & Exclusions",
    description: "Monitor behaviour incidents and exclusions.",
    category: "Bromcom",
    tag: "",
    href: "/analytics/education/bromcom-suspensions-exclusions",
    component: () => <PowerBIReportPage reportKey="bromcom-suspensions-exclusions" title="Suspensions & Exclusions" />,
    comingSoon: false,
  },
  {
    id: "dret-academy-report",
    name: "Academy Report",
    description: "Academy-level performance and analysis.",
    category: "DRET",
    tag: "",
    href: "/analytics/education/dret-academy-report",
    component: () => <PowerBIReportPage reportKey="dret-academy-report" title="DRET Academy Report" />,
    comingSoon: false,
  },
  {
    id: "mat-comparison-analysis-ks2",
    name: "MAT KS2 Comparison",
    description: "Compare KS2 outcomes across academies.",
    category: "DRET",
    tag: "",
    href: "/analytics/education/mat-comparison-analysis-ks2",
    component: () => <PowerBIReportPage reportKey="mat-comparison-analysis-ks2" title="MAT KS2 Comparison" />,
    comingSoon: false,
  },
  {
    id: "mat-comparison-analysis-ks4",
    name: "MAT KS4 Comparison",
    description: "Compare KS4 outcomes across academies.",
    category: "DRET",
    tag: "",
    href: "/analytics/education/mat-comparison-analysis-ks4",
    component: () => <PowerBIReportPage reportKey="mat-comparison-analysis-ks4" title="MAT KS4 Comparison" />,
    comingSoon: false,
  }
];
