import LessonPlanningTool from "../tools/001";
import ReportWritingTool from "../tools/002";
import ExclusionReportTool from "../tools/003";
import CASEParagraphFeedback from "../tools/004";
import CASEParagraphFeedbackStudent from "../tools/005";

// Dummy component for placeholder tools
const DummyTool = () => <div>Coming soon...</div>;

export const toolsConfig = [
  {
    id: "report-writer",
    name: "Report Writer",
    description: "Generate constructive student reports.",
    category: ["Assessment"],
    tag: "New",
    href: "/ai/tool/report-writer",
    component: ReportWritingTool,
    comingSoon: false,
  },
  {
    id: "lesson-planner",
    name: "Maths Lesson Planner",
    description: "Plan and manage lessons with ease.",
    category: ["Planning", "Maths"],
    tag: "New",
    href: "/ai/tool/lesson-planner",
    component: LessonPlanningTool,
    comingSoon: false,
  },
  {
    id: "exclusion-report",
    name: "Exclusion Report",
    description: "Generate detailed exclusion reports.",
    category: ["Admin"],
    tag: "New",
    href: "/ai/tool/exclusion-report",
    component: ExclusionReportTool,
    comingSoon: false,
  },
  {
    id: "case-paragraph",
    name: "CASE Paragraph Feedback",
    description: "Provide feedback on student CASE paragraphs.",
    category: ["Assessment", "History"],
    tag: "New",
    href: "/ai/tool/case-paragraph",
    component: CASEParagraphFeedback,
    comingSoon: false,
  },
  {
    id: "case-paragraph-student",
    name: "Testing",
    description: "Testing",
    category: ["Assessment", "Geography"],
    tag: "New",
    href: "/ai/tool/case-paragraph-student",
    component: CASEParagraphFeedbackStudent,
    comingSoon: false,
  },

  // Expanded dummy tools
  {
    id: "knowledge-wardrobe",
    name: "Knowledge Wardrobe Generator",
    description: "Organise History content by themes, periods, or figures.",
    category: ["History", "Planning"],
    tag: "New",
    href: "/ai/tool/knowledge-wardrobe",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "mfl-keyword-gen",
    name: "MFL Keyword Generator",
    description: "Translate and list key vocab for different topics.",
    category: ["MFL", "Planning"],
    tag: "New",
    href: "/ai/tool/mfl-keyword-gen",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "eal-adapt",
    name: "EAL Work Adaptor",
    description: "Adapt worksheets and texts for EAL learners.",
    category: ["Inclusion", "Support"],
    tag: "New",
    href: "/ai/tool/eal-adapt",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "history-exam-feedback",
    name: "History Exam Feedback",
    description: "Generate feedback for GCSE history questions.",
    category: ["Assessment", "History"],
    tag: "New",
    href: "/ai/tool/history-exam-feedback",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "maths-marking-tool",
    name: "Maths Marking Tool",
    description: "Mark and explain maths responses step-by-step.",
    category: ["Assessment", "Maths"],
    tag: "New",
    href: "/ai/tool/maths-marking-tool",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "primary-phonics-helper",
    name: "Phonics Prompt Generator",
    description: "Create phonics-based activities for early readers.",
    category: ["Primary", "Literacy"],
    tag: "New",
    href: "/ai/tool/primary-phonics-helper",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "ks1-story-planner",
    name: "KS1 Story Planner",
    description: "Support younger pupils in developing narrative structure.",
    category: ["Primary", "English"],
    tag: "New",
    href: "/ai/tool/ks1-story-planner",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "ta-taskboard",
    name: "TA Task Board Generator",
    description: "Generate visual task boards for support staff use.",
    category: ["Inclusion", "Primary", "Support"],
    tag: "New",
    href: "/ai/tool/ta-taskboard",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "science-practical-planner",
    name: "Science Practical Planner",
    description: "Plan practical science tasks with equipment lists.",
    category: ["Science", "Planning"],
    tag: "New",
    href: "/ai/tool/science-practical-planner",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "sat-analysis-helper",
    name: "KS2 SATs Analysis Helper",
    description: "Summarise trends and group gaps from KS2 SATs data.",
    category: ["Primary", "Data"],
    tag: "New",
    href: "/ai/tool/sat-analysis-helper",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "comprehension-question-creator",
    name: "Reading Comprehension Question Creator",
    description: "Generate tailored questions from reading texts.",
    category: ["English", "Assessment"],
    tag: "New",
    href: "/ai/tool/comprehension-question-creator",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "behaviour-incident-rewriter",
    name: "Behaviour Incident Rewriter",
    description: "Rewrite behaviour logs in professional, neutral tone.",
    category: ["Admin", "Inclusion"],
    tag: "New",
    href: "/ai/tool/behaviour-incident-rewriter",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "reading-progress-reports",
    name: "Reading Progress Reports",
    description: "Generate termly reading summaries from teacher notes.",
    category: ["Assessment", "Primary", "English"],
    tag: "New",
    href: "/ai/tool/reading-progress-reports",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "ks3-starter-idea-bank",
    name: "KS3 Starter Idea Bank",
    description: "Quick warm-up activities by subject and topic.",
    category: ["Planning", "Secondary"],
    tag: "New",
    href: "/ai/tool/ks3-starter-idea-bank",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "visual-timetable-gen",
    name: "Visual Timetable Generator",
    description: "Create daily visual timetables for pupils with SEND.",
    category: ["Inclusion", "Primary"],
    tag: "New",
    href: "/ai/tool/visual-timetable-gen",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "maths-retrieval-warmups",
    name: "Maths Retrieval Warm-ups",
    description: "Generate daily recall starters from curriculum maps.",
    category: ["Maths", "Planning"],
    tag: "New",
    href: "/ai/tool/maths-retrieval-warmups",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "do-now-generator",
    name: "Do Now Generator",
    description: "Generate do-now tasks for any subject.",
    category: ["Planning", "All Subjects"],
    tag: "New",
    href: "/ai/tool/ta-deployment-scheduler",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "marking-feedback-pool",
    name: "Marking Feedback Pool",
    description: "Pull banked comments and personalised suggestions.",
    category: ["Assessment", "English", "All Subjects"],
    tag: "New",
    href: "/ai/tool/marking-feedback-pool",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "homework-creator",
    name: "Homework Generator",
    description: "Generate differentiated homework tasks by topic.",
    category: ["Planning", "All Subjects"],
    tag: "New",
    href: "/ai/tool/homework-creator",
    component: DummyTool,
    comingSoon: false,
  },
  {
    id: "transition-info-sheet",
    name: "Y6 to Y7 Transition Info Sheet",
    description: "Auto-summarise SEND/EAL/academic notes for transition.",
    category: ["Primary", "Inclusion", "Admin"],
    tag: "New",
    href: "/ai/tool/transition-info-sheet",
    component: DummyTool,
    comingSoon: false,
  },
];
