import $001 from "./tools/001";
import $002 from "./tools/002";
import $003 from "./tools/003";

// Placeholder stubs (use ToolTemplate or null component as placeholder)
const Placeholder = () => null;

export const toolsConfig = [
  {
    id: "001",
    name: "Lesson Planning",
    description: "Write professional, individualised lessons",
    category: "Planning",
    tag: "New",
    href: "/001",
    component: $001,
  },
  {
    id: "002",
    name: "Feedback Generator",
    description: "Generate detailed, personalised feedback",
    category: "Assessment",
    tag: "New",
    href: "/002",
    component: $002,
  },
  {
    id: "003",
    name: "Exam Question Generator",
    description: "Create custom exam-style questions",
    category: "Assessment",
    tag: "New",
    href: "/003",
    component: $003,
  },

  // 🆕 Placeholder tools
  {
    id: "004",
    name: "Homework Designer",
    description: "Create homework tasks with automated feedback",
    category: "Planning",
    tag: "Hot",
    href: "/004",
    component: Placeholder,
  },
  {
    id: "005",
    name: "Quiz Builder",
    description: "Generate quizzes from topics and key terms",
    category: "Assessment",
    tag: "New",
    href: "/005",
    component: Placeholder,
  },
  {
    id: "006",
    name: "Classroom Icebreakers",
    description: "Suggest fun classroom starter activities",
    category: "Leadership",
    tag: "New",
    href: "/006",
    component: Placeholder,
  },
  {
    id: "007",
    name: "Curriculum Mapper",
    description: "Align lessons to national curriculum frameworks",
    category: "Planning",
    tag: "",
    href: "/007",
    component: Placeholder,
  },
  {
    id: "008",
    name: "Reading Comprehension Assistant",
    description: "Generate age-appropriate comprehension tasks",
    category: "Inclusion",
    tag: "Hot",
    href: "/008",
    component: Placeholder,
  },
  {
    id: "009",
    name: "Target Tracker",
    description: "Generate student target statements",
    category: "Inclusion",
    tag: "New",
    href: "/009",
    component: Placeholder,
  },
  {
    id: "010",
    name: "Behaviour Report Writer",
    description: "Automate student report comments and concerns",
    category: "Admin",
    tag: "",
    href: "/010",
    component: Placeholder,
  },
  {
    id: "011",
    name: "CPD Planner",
    description: "Generate personalised CPD suggestions for staff",
    category: "Leadership",
    tag: "",
    href: "/011",
    component: Placeholder,
  },
  {
    id: "012",
    name: "Data Explainer",
    description: "Explain trends in performance data for parents",
    category: "Admin",
    tag: "",
    href: "/012",
    component: Placeholder,
  },
  {
    id: "013",
    name: "Parent Letter Generator",
    description: "Generate professional communication for parents",
    category: "Admin",
    tag: "New",
    href: "/013",
    component: Placeholder,
  },
  {
    id: "014",
    name: "SEN Strategy Assistant",
    description: "Suggest strategies based on SEN category",
    category: "Inclusion",
    tag: "Hot",
    href: "/014",
    component: Placeholder,
  },
  {
    id: "015",
    name: "Presentation Enhancer",
    description: "Improve or rewrite slide content automatically",
    category: "Admin",
    tag: "New",
    href: "/015",
    component: Placeholder,
  },
];
